-- 판교 1~10반 일정 변경분 반영 (professor 공지 기준)
update schedule set week_no = 1, subject = '팀빌딩, Git 이해/활용 (5h)', instructor = '한성훈' where class_id = (select id from class_group where name = '10반') and date = date '2026-07-14';
update schedule set week_no = 6, subject = 'Spring AI', instructor = '정윤석' where class_id = (select id from class_group where name = '10반') and date = date '2026-08-18';
update schedule set week_no = 6, subject = 'Spring AI', instructor = '정윤석' where class_id = (select id from class_group where name = '10반') and date = date '2026-08-19';
update schedule set week_no = 6, subject = 'Spring AI', instructor = '정윤석' where class_id = (select id from class_group where name = '10반') and date = date '2026-08-20';
update schedule set week_no = 9, subject = '쿠버네티스 이해 및 애플리케이션 배포', instructor = '정윤석' where class_id = (select id from class_group where name = '10반') and date = date '2026-09-07';
update schedule set week_no = 9, subject = '쿠버네티스 이해 및 애플리케이션 배포', instructor = '정윤석' where class_id = (select id from class_group where name = '10반') and date = date '2026-09-08';
update schedule set week_no = 12, subject = '모델 서빙 및 AIOps 구성', instructor = '임성열' where class_id = (select id from class_group where name = '10반') and date = date '2026-09-30';
update schedule set week_no = 12, subject = '모델 서빙 및 AIOps 구성', instructor = '임성열' where class_id = (select id from class_group where name = '10반') and date = date '2026-10-01';
update schedule set week_no = 12, subject = '모델 서빙 및 AIOps 구성', instructor = '임성열' where class_id = (select id from class_group where name = '10반') and date = date '2026-10-02';
update schedule set week_no = 13, subject = 'AI Agent 설계 및 구축', instructor = '김성영' where class_id = (select id from class_group where name = '10반') and date = date '2026-10-06';
update schedule set week_no = 13, subject = 'AI Agent 설계 및 구축', instructor = '김성영' where class_id = (select id from class_group where name = '10반') and date = date '2026-10-07';
update schedule set week_no = 13, subject = 'Vector DB', instructor = '김성영' where class_id = (select id from class_group where name = '10반') and date = date '2026-10-08';
update schedule set week_no = 14, subject = 'DevOps 이해 및 활용', instructor = '김성영' where class_id = (select id from class_group where name = '10반') and date = date '2026-10-12';
update schedule set week_no = 14, subject = 'DevOps 이해 및 활용', instructor = '김성영' where class_id = (select id from class_group where name = '10반') and date = date '2026-10-13';
update schedule set week_no = 14, subject = '쿠버네티스 실무 심화', instructor = '김성영' where class_id = (select id from class_group where name = '10반') and date = date '2026-10-14';
update schedule set week_no = 14, subject = '쿠버네티스 실무 심화', instructor = '조재형' where class_id = (select id from class_group where name = '10반') and date = date '2026-10-15';
update schedule set week_no = 14, subject = '쿠버네티스 실무 심화', instructor = '조재형' where class_id = (select id from class_group where name = '10반') and date = date '2026-10-16';
update schedule set week_no = 15, subject = '데이터 분석 mini-Project', instructor = '박보경' where class_id = (select id from class_group where name = '10반') and date = date '2026-10-19';
update schedule set week_no = 15, subject = '데이터 분석 mini-Project', instructor = '박보경' where class_id = (select id from class_group where name = '10반') and date = date '2026-10-20';
update schedule set week_no = 15, subject = 'AI Agent Capstone (MCP)', instructor = '박보경' where class_id = (select id from class_group where name = '10반') and date = date '2026-10-21';
update schedule set week_no = 15, subject = 'AI Agent Capstone (MCP)', instructor = '박보경' where class_id = (select id from class_group where name = '10반') and date = date '2026-10-22';
update schedule set week_no = 15, subject = 'AI Agent Capstone (MCP)', instructor = '박보경' where class_id = (select id from class_group where name = '10반') and date = date '2026-10-23';
update schedule set week_no = 16, subject = 'AI 프로젝트 방법론 (1시~)', instructor = null where class_id = (select id from class_group where name = '10반') and date = date '2026-10-29';
update schedule set week_no = 17, subject = '특강 (도메인 특강)', instructor = '도메인특강' where class_id = (select id from class_group where name = '10반') and date = date '2026-11-06';
update schedule set week_no = 10, subject = '모델 개발 및 최적화', instructor = '김영희' where class_id = (select id from class_group where name = '1반') and date = date '2026-09-16';
update schedule set week_no = 10, subject = '모델 개발 및 최적화', instructor = '김영희' where class_id = (select id from class_group where name = '1반') and date = date '2026-09-17';
update schedule set week_no = 14, subject = '데이터 분석 mini-Project', instructor = '이은호' where class_id = (select id from class_group where name = '1반') and date = date '2026-10-13';
update schedule set week_no = 14, subject = '데이터 분석 mini-Project', instructor = '이은호' where class_id = (select id from class_group where name = '1반') and date = date '2026-10-14';
update schedule set week_no = 14, subject = 'AI Agent 설계 및 구축', instructor = '하만석' where class_id = (select id from class_group where name = '1반') and date = date '2026-10-15';
update schedule set week_no = 14, subject = 'AI Agent 설계 및 구축', instructor = '하만석' where class_id = (select id from class_group where name = '1반') and date = date '2026-10-16';
update schedule set week_no = 16, subject = 'DevOps 이해 및 활용', instructor = '정경윤' where class_id = (select id from class_group where name = '1반') and date = date '2026-10-27';
update schedule set week_no = 16, subject = 'DevOps 이해 및 활용', instructor = '정경윤' where class_id = (select id from class_group where name = '1반') and date = date '2026-10-28';
update schedule set week_no = 4, subject = '머신러닝 및 딥러닝 이해', instructor = '박길식' where class_id = (select id from class_group where name = '2반') and date = date '2026-08-06';
update schedule set week_no = 4, subject = '머신러닝 및 딥러닝 이해', instructor = '박길식' where class_id = (select id from class_group where name = '2반') and date = date '2026-08-07';
update schedule set week_no = 5, subject = '머신러닝 및 딥러닝 이해', instructor = '박길식' where class_id = (select id from class_group where name = '2반') and date = date '2026-08-10';
update schedule set week_no = 5, subject = '스마트 데이터 이해 및 활용', instructor = '김경난' where class_id = (select id from class_group where name = '2반') and date = date '2026-08-11';
update schedule set week_no = 5, subject = '스마트 데이터 이해 및 활용', instructor = '김경난' where class_id = (select id from class_group where name = '2반') and date = date '2026-08-12';
update schedule set week_no = 5, subject = '스마트 데이터 이해 및 활용', instructor = '김경난' where class_id = (select id from class_group where name = '2반') and date = date '2026-08-13';
update schedule set week_no = 5, subject = '스마트 데이터 이해 및 활용', instructor = '김경난' where class_id = (select id from class_group where name = '2반') and date = date '2026-08-14';
update schedule set week_no = 6, subject = 'sLLM 구현 및 Fine Tunning', instructor = '한성훈' where class_id = (select id from class_group where name = '2반') and date = date '2026-08-18';
update schedule set week_no = 6, subject = 'sLLM 구현 및 Fine Tunning', instructor = '한성훈' where class_id = (select id from class_group where name = '2반') and date = date '2026-08-19';
update schedule set week_no = 6, subject = '컨테이너 이해 및 애플리케이션 컨테이너화', instructor = '하만석' where class_id = (select id from class_group where name = '2반') and date = date '2026-08-20';
update schedule set week_no = 6, subject = '컨테이너 이해 및 애플리케이션 컨테이너화', instructor = '하만석' where class_id = (select id from class_group where name = '2반') and date = date '2026-08-21';
update schedule set week_no = 7, subject = 'Front-framework: Vue.js', instructor = '강병호' where class_id = (select id from class_group where name = '2반') and date = date '2026-08-24';
update schedule set week_no = 7, subject = 'Front-framework: Vue.js', instructor = '강병호' where class_id = (select id from class_group where name = '2반') and date = date '2026-08-25';
update schedule set week_no = 7, subject = 'Front-framework: Vue.js', instructor = '강병호' where class_id = (select id from class_group where name = '2반') and date = date '2026-08-26';
update schedule set week_no = 7, subject = 'Front-framework: Vue.js', instructor = '강병호' where class_id = (select id from class_group where name = '2반') and date = date '2026-08-27';
update schedule set week_no = 8, subject = '특강 (도메인특강, 프로젝트 현장 사례)', instructor = '도메인특강' where class_id = (select id from class_group where name = '2반') and date = date '2026-09-04';
update schedule set week_no = 10, subject = '모델 개발 및 최적화', instructor = '박병선' where class_id = (select id from class_group where name = '2반') and date = date '2026-09-16';
update schedule set week_no = 10, subject = '모델 개발 및 최적화', instructor = '박병선' where class_id = (select id from class_group where name = '2반') and date = date '2026-09-17';
update schedule set week_no = 11, subject = '모델 서빙 및 AIOps 구성', instructor = '박창렴' where class_id = (select id from class_group where name = '2반') and date = date '2026-09-22';
update schedule set week_no = 15, subject = 'AI Agent Capstone (MCP)', instructor = '정윤석' where class_id = (select id from class_group where name = '2반') and date = date '2026-10-19';
update schedule set week_no = 15, subject = 'AI Agent Capstone (MCP)', instructor = '정윤석' where class_id = (select id from class_group where name = '2반') and date = date '2026-10-20';
update schedule set week_no = 15, subject = 'AI Agent Capstone (MCP)', instructor = '정윤석' where class_id = (select id from class_group where name = '2반') and date = date '2026-10-21';
update schedule set week_no = 16, subject = 'AI 프로젝트 방법론 (9시~)', instructor = '백정열' where class_id = (select id from class_group where name = '2반') and date = date '2026-10-29';
update schedule set week_no = 4, subject = '머신러닝 및 딥러닝 이해', instructor = '배기주' where class_id = (select id from class_group where name = '3반') and date = date '2026-08-06';
update schedule set week_no = 4, subject = '머신러닝 및 딥러닝 이해', instructor = '배기주' where class_id = (select id from class_group where name = '3반') and date = date '2026-08-07';
update schedule set week_no = 5, subject = '머신러닝 및 딥러닝 이해', instructor = '배기주' where class_id = (select id from class_group where name = '3반') and date = date '2026-08-10';
update schedule set week_no = 7, subject = 'Front-framework: Vue.js', instructor = '김범준' where class_id = (select id from class_group where name = '3반') and date = date '2026-08-24';
update schedule set week_no = 7, subject = 'Front-framework: Vue.js', instructor = '김범준' where class_id = (select id from class_group where name = '3반') and date = date '2026-08-25';
update schedule set week_no = 7, subject = 'Front-framework: Vue.js', instructor = '김범준' where class_id = (select id from class_group where name = '3반') and date = date '2026-08-26';
update schedule set week_no = 7, subject = 'Front-framework: Vue.js', instructor = '김범준' where class_id = (select id from class_group where name = '3반') and date = date '2026-08-27';
update schedule set week_no = 8, subject = 'Agile 방법론 및 MSA 개발', instructor = '이상희' where class_id = (select id from class_group where name = '3반') and date = date '2026-09-02';
update schedule set week_no = 8, subject = 'Agile 방법론 및 MSA 개발', instructor = '이상희' where class_id = (select id from class_group where name = '3반') and date = date '2026-09-03';
update schedule set week_no = 10, subject = '모델 개발 및 최적화', instructor = '김범준' where class_id = (select id from class_group where name = '3반') and date = date '2026-09-16';
update schedule set week_no = 10, subject = '모델 개발 및 최적화', instructor = '김범준' where class_id = (select id from class_group where name = '3반') and date = date '2026-09-17';
update schedule set week_no = 10, subject = '쿠버네티스 이해 및 애플리케이션 배포', instructor = '이용우' where class_id = (select id from class_group where name = '3반') and date = date '2026-09-18';
update schedule set week_no = 11, subject = '쿠버네티스 이해 및 애플리케이션 배포', instructor = '이용우' where class_id = (select id from class_group where name = '3반') and date = date '2026-09-21';
update schedule set week_no = 13, subject = 'Vector DB', instructor = '백정열' where class_id = (select id from class_group where name = '3반') and date = date '2026-10-06';
update schedule set week_no = 13, subject = '쿠버네티스 실무 심화', instructor = '정윤석' where class_id = (select id from class_group where name = '3반') and date = date '2026-10-07';
update schedule set week_no = 13, subject = '쿠버네티스 실무 심화', instructor = '정윤석' where class_id = (select id from class_group where name = '3반') and date = date '2026-10-08';
update schedule set week_no = 14, subject = '쿠버네티스 실무 심화', instructor = '정윤석' where class_id = (select id from class_group where name = '3반') and date = date '2026-10-12';
update schedule set week_no = 16, subject = 'DevOps 이해 및 활용', instructor = '김범준' where class_id = (select id from class_group where name = '3반') and date = date '2026-10-27';
update schedule set week_no = 16, subject = 'DevOps 이해 및 활용', instructor = '김범준' where class_id = (select id from class_group where name = '3반') and date = date '2026-10-28';
update schedule set week_no = 4, subject = '실전 Feature Engineering', instructor = '김범준' where class_id = (select id from class_group where name = '4반') and date = date '2026-08-05';
update schedule set week_no = 4, subject = '머신러닝 및 딥러닝 이해', instructor = '송영옥' where class_id = (select id from class_group where name = '4반') and date = date '2026-08-06';
update schedule set week_no = 4, subject = '머신러닝 및 딥러닝 이해', instructor = '송영옥' where class_id = (select id from class_group where name = '4반') and date = date '2026-08-07';
update schedule set week_no = 5, subject = '머신러닝 및 딥러닝 이해', instructor = '송영옥' where class_id = (select id from class_group where name = '4반') and date = date '2026-08-10';
update schedule set week_no = 5, subject = '스마트 데이터 이해 및 활용', instructor = '백정열' where class_id = (select id from class_group where name = '4반') and date = date '2026-08-11';
update schedule set week_no = 5, subject = '스마트 데이터 이해 및 활용', instructor = '백정열' where class_id = (select id from class_group where name = '4반') and date = date '2026-08-12';
update schedule set week_no = 5, subject = '스마트 데이터 이해 및 활용', instructor = '백정열' where class_id = (select id from class_group where name = '4반') and date = date '2026-08-13';
update schedule set week_no = 5, subject = '스마트 데이터 이해 및 활용', instructor = '백정열' where class_id = (select id from class_group where name = '4반') and date = date '2026-08-14';
update schedule set week_no = 8, subject = 'Agile 방법론 및 MSA 개발', instructor = '임성열' where class_id = (select id from class_group where name = '4반') and date = date '2026-09-02';
update schedule set week_no = 8, subject = 'Agile 방법론 및 MSA 개발', instructor = '임성열' where class_id = (select id from class_group where name = '4반') and date = date '2026-09-03';
update schedule set week_no = 9, subject = '생성형 AI 서비스 개발의 이해/활용 (LangChain)', instructor = '하만석' where class_id = (select id from class_group where name = '4반') and date = date '2026-09-11';
update schedule set week_no = 10, subject = '생성형 AI 서비스 개발의 이해/활용 (LangChain)', instructor = '하만석' where class_id = (select id from class_group where name = '4반') and date = date '2026-09-14';
update schedule set week_no = 10, subject = '생성형 AI 서비스 개발의 이해/활용 (LangChain)', instructor = '하만석' where class_id = (select id from class_group where name = '4반') and date = date '2026-09-15';
update schedule set week_no = 10, subject = '모델 개발 및 최적화', instructor = '박창렴' where class_id = (select id from class_group where name = '4반') and date = date '2026-09-16';
update schedule set week_no = 10, subject = '모델 개발 및 최적화', instructor = '박창렴' where class_id = (select id from class_group where name = '4반') and date = date '2026-09-17';
update schedule set week_no = 10, subject = '쿠버네티스 이해 및 애플리케이션 배포', instructor = '박보경' where class_id = (select id from class_group where name = '4반') and date = date '2026-09-18';
update schedule set week_no = 11, subject = '쿠버네티스 이해 및 애플리케이션 배포', instructor = '박보경' where class_id = (select id from class_group where name = '4반') and date = date '2026-09-21';
update schedule set week_no = 11, subject = '특강(취업특강), 2시 종료', instructor = null where class_id = (select id from class_group where name = '4반') and date = date '2026-09-23';
update schedule set week_no = 12, subject = 'RAG Pipeline 설계 및 구축', instructor = '송영옥' where class_id = (select id from class_group where name = '4반') and date = date '2026-09-30';
update schedule set week_no = 12, subject = 'RAG Pipeline 설계 및 구축', instructor = '송영옥' where class_id = (select id from class_group where name = '4반') and date = date '2026-10-01';
update schedule set week_no = 12, subject = 'RAG Pipeline 설계 및 구축', instructor = '송영옥' where class_id = (select id from class_group where name = '4반') and date = date '2026-10-02';
update schedule set week_no = 13, subject = '쿠버네티스 실무 심화', instructor = '박보경' where class_id = (select id from class_group where name = '4반') and date = date '2026-10-07';
update schedule set week_no = 13, subject = '쿠버네티스 실무 심화', instructor = '박보경' where class_id = (select id from class_group where name = '4반') and date = date '2026-10-08';
update schedule set week_no = 14, subject = '쿠버네티스 실무 심화', instructor = '박보경' where class_id = (select id from class_group where name = '4반') and date = date '2026-10-12';
update schedule set week_no = 14, subject = 'AI Agent 설계 및 구축', instructor = '이미애' where class_id = (select id from class_group where name = '4반') and date = date '2026-10-15';
update schedule set week_no = 14, subject = 'AI Agent 설계 및 구축', instructor = '이미애' where class_id = (select id from class_group where name = '4반') and date = date '2026-10-16';
update schedule set week_no = 16, subject = '특강 (도메인 특강)', instructor = '도메인특강' where class_id = (select id from class_group where name = '4반') and date = date '2026-10-30';
update schedule set week_no = 5, subject = '스마트 데이터 이해 및 활용', instructor = '윤재성' where class_id = (select id from class_group where name = '5반') and date = date '2026-08-11';
update schedule set week_no = 5, subject = '스마트 데이터 이해 및 활용', instructor = '윤재성' where class_id = (select id from class_group where name = '5반') and date = date '2026-08-12';
update schedule set week_no = 5, subject = '스마트 데이터 이해 및 활용', instructor = '윤재성' where class_id = (select id from class_group where name = '5반') and date = date '2026-08-13';
update schedule set week_no = 5, subject = '스마트 데이터 이해 및 활용', instructor = '윤재성' where class_id = (select id from class_group where name = '5반') and date = date '2026-08-14';
update schedule set week_no = 6, subject = 'sLLM 구현 및 Fine Tunning', instructor = '박병선' where class_id = (select id from class_group where name = '5반') and date = date '2026-08-18';
update schedule set week_no = 6, subject = 'sLLM 구현 및 Fine Tunning', instructor = '박병선' where class_id = (select id from class_group where name = '5반') and date = date '2026-08-19';
update schedule set week_no = 6, subject = '컨테이너 이해 및 애플리케이션 컨테이너화', instructor = '백정열' where class_id = (select id from class_group where name = '5반') and date = date '2026-08-20';
update schedule set week_no = 6, subject = '컨테이너 이해 및 애플리케이션 컨테이너화', instructor = '백정열' where class_id = (select id from class_group where name = '5반') and date = date '2026-08-21';
update schedule set week_no = 9, subject = '생성형 AI 서비스 개발의 이해/활용 (LangChain)', instructor = '권기창' where class_id = (select id from class_group where name = '5반') and date = date '2026-09-11';
update schedule set week_no = 10, subject = '생성형 AI 서비스 개발의 이해/활용 (LangChain)', instructor = '권기창' where class_id = (select id from class_group where name = '5반') and date = date '2026-09-14';
update schedule set week_no = 10, subject = '생성형 AI 서비스 개발의 이해/활용 (LangChain)', instructor = '권기창' where class_id = (select id from class_group where name = '5반') and date = date '2026-09-15';
update schedule set week_no = 11, subject = '모델 서빙 및 AIOps 구성', instructor = '조재형' where class_id = (select id from class_group where name = '5반') and date = date '2026-09-22';
update schedule set week_no = 12, subject = 'RAG Pipeline 설계 및 구축', instructor = '권기창' where class_id = (select id from class_group where name = '5반') and date = date '2026-09-30';
update schedule set week_no = 12, subject = 'RAG Pipeline 설계 및 구축', instructor = '권기창' where class_id = (select id from class_group where name = '5반') and date = date '2026-10-01';
update schedule set week_no = 12, subject = 'RAG Pipeline 설계 및 구축', instructor = '권기창' where class_id = (select id from class_group where name = '5반') and date = date '2026-10-02';
update schedule set week_no = 13, subject = 'Vector DB', instructor = '김범준' where class_id = (select id from class_group where name = '5반') and date = date '2026-10-06';
update schedule set week_no = 13, subject = '쿠버네티스 실무 심화', instructor = '이상희' where class_id = (select id from class_group where name = '5반') and date = date '2026-10-07';
update schedule set week_no = 13, subject = '쿠버네티스 실무 심화', instructor = '이상희' where class_id = (select id from class_group where name = '5반') and date = date '2026-10-08';
update schedule set week_no = 14, subject = '쿠버네티스 실무 심화', instructor = '이상희' where class_id = (select id from class_group where name = '5반') and date = date '2026-10-12';
update schedule set week_no = 14, subject = '데이터 분석 mini-Project', instructor = '장경희' where class_id = (select id from class_group where name = '5반') and date = date '2026-10-13';
update schedule set week_no = 14, subject = '데이터 분석 mini-Project', instructor = '장경희' where class_id = (select id from class_group where name = '5반') and date = date '2026-10-14';
update schedule set week_no = 14, subject = 'AI Agent 설계 및 구축', instructor = '장경희' where class_id = (select id from class_group where name = '5반') and date = date '2026-10-15';
update schedule set week_no = 14, subject = 'AI Agent 설계 및 구축', instructor = '장경희' where class_id = (select id from class_group where name = '5반') and date = date '2026-10-16';
update schedule set week_no = 15, subject = 'AI Agent Capstone (MCP)', instructor = '김성영' where class_id = (select id from class_group where name = '5반') and date = date '2026-10-19';
update schedule set week_no = 15, subject = 'AI Agent Capstone (MCP)', instructor = '김성영' where class_id = (select id from class_group where name = '5반') and date = date '2026-10-20';
update schedule set week_no = 15, subject = 'AI Agent Capstone (MCP)', instructor = '김성영' where class_id = (select id from class_group where name = '5반') and date = date '2026-10-21';
update schedule set week_no = 16, subject = 'AI 프로젝트 방법론 (9시~)', instructor = null where class_id = (select id from class_group where name = '5반') and date = date '2026-10-29';
update schedule set week_no = 4, subject = 'Front-framework: Vue.js', instructor = '김영희' where class_id = (select id from class_group where name = '6반') and date = date '2026-08-04';
update schedule set week_no = 8, subject = '머신러닝 및 딥러닝 이해', instructor = '김경난' where class_id = (select id from class_group where name = '6반') and date = date '2026-09-01';
update schedule set week_no = 8, subject = '머신러닝 및 딥러닝 이해', instructor = '김경난' where class_id = (select id from class_group where name = '6반') and date = date '2026-09-02';
update schedule set week_no = 8, subject = '머신러닝 및 딥러닝 이해', instructor = '김경난' where class_id = (select id from class_group where name = '6반') and date = date '2026-09-03';
update schedule set week_no = 10, subject = '웹 서비스 개발 mini-Project', instructor = '백정열' where class_id = (select id from class_group where name = '6반') and date = date '2026-09-15';
update schedule set week_no = 10, subject = '웹 서비스 개발 mini-Project', instructor = '백정열' where class_id = (select id from class_group where name = '6반') and date = date '2026-09-16';
update schedule set week_no = 10, subject = '웹 서비스 개발 mini-Project', instructor = '백정열' where class_id = (select id from class_group where name = '6반') and date = date '2026-09-17';
update schedule set week_no = 14, subject = '쿠버네티스 실무 심화', instructor = '이상희' where class_id = (select id from class_group where name = '6반') and date = date '2026-10-14';
update schedule set week_no = 14, subject = '쿠버네티스 실무 심화', instructor = '이상희' where class_id = (select id from class_group where name = '6반') and date = date '2026-10-15';
update schedule set week_no = 14, subject = '쿠버네티스 실무 심화', instructor = '이상희' where class_id = (select id from class_group where name = '6반') and date = date '2026-10-16';
update schedule set week_no = 15, subject = '데이터 분석 mini-Project', instructor = '이상희' where class_id = (select id from class_group where name = '6반') and date = date '2026-10-19';
update schedule set week_no = 15, subject = '데이터 분석 mini-Project', instructor = '이상희' where class_id = (select id from class_group where name = '6반') and date = date '2026-10-20';
update schedule set week_no = 15, subject = 'AI Agent Capstone (MCP)', instructor = '이상희' where class_id = (select id from class_group where name = '6반') and date = date '2026-10-21';
update schedule set week_no = 15, subject = 'AI Agent Capstone (MCP)', instructor = '이상희' where class_id = (select id from class_group where name = '6반') and date = date '2026-10-22';
update schedule set week_no = 15, subject = 'AI Agent Capstone (MCP)', instructor = '이상희' where class_id = (select id from class_group where name = '6반') and date = date '2026-10-23';
update schedule set week_no = 16, subject = 'AI 서비스 개발 Mini-project', instructor = '이상희' where class_id = (select id from class_group where name = '6반') and date = date '2026-10-26';
update schedule set week_no = 16, subject = 'AI 서비스 개발 Mini-project', instructor = '이상희' where class_id = (select id from class_group where name = '6반') and date = date '2026-10-27';
update schedule set week_no = 16, subject = 'AI 서비스 개발 Mini-project', instructor = '이상희' where class_id = (select id from class_group where name = '6반') and date = date '2026-10-28';
update schedule set week_no = 4, subject = '데이터 분석을 위한 Python 이해', instructor = '김범준' where class_id = (select id from class_group where name = '7반') and date = date '2026-08-06';
update schedule set week_no = 4, subject = '데이터 분석을 위한 Python 이해', instructor = '김범준' where class_id = (select id from class_group where name = '7반') and date = date '2026-08-07';
update schedule set week_no = 5, subject = 'Java, SpringBoot, Rest API 구현', instructor = '김영희' where class_id = (select id from class_group where name = '7반') and date = date '2026-08-10';
update schedule set week_no = 5, subject = 'Java, SpringBoot, Rest API 구현', instructor = '김영희' where class_id = (select id from class_group where name = '7반') and date = date '2026-08-11';
update schedule set week_no = 5, subject = 'Java, SpringBoot, Rest API 구현', instructor = '김영희' where class_id = (select id from class_group where name = '7반') and date = date '2026-08-12';
update schedule set week_no = 5, subject = 'Java, SpringBoot, Rest API 구현', instructor = '김영희' where class_id = (select id from class_group where name = '7반') and date = date '2026-08-13';
update schedule set week_no = 5, subject = 'Java, SpringBoot, Rest API 구현', instructor = '김영희' where class_id = (select id from class_group where name = '7반') and date = date '2026-08-14';
update schedule set week_no = 6, subject = 'Spring AI', instructor = '김경난' where class_id = (select id from class_group where name = '7반') and date = date '2026-08-18';
update schedule set week_no = 6, subject = 'Spring AI', instructor = '김경난' where class_id = (select id from class_group where name = '7반') and date = date '2026-08-19';
update schedule set week_no = 6, subject = 'Spring AI', instructor = '김경난' where class_id = (select id from class_group where name = '7반') and date = date '2026-08-20';
update schedule set week_no = 6, subject = '컨테이너 이해 및 애플리케이션 컨테이너화', instructor = '이용우' where class_id = (select id from class_group where name = '7반') and date = date '2026-08-21';
update schedule set week_no = 7, subject = '컨테이너 이해 및 애플리케이션 컨테이너화', instructor = '이용우' where class_id = (select id from class_group where name = '7반') and date = date '2026-08-24';
update schedule set week_no = 7, subject = '특강(취업특강)', instructor = '최헌영' where class_id = (select id from class_group where name = '7반') and date = date '2026-08-25';
update schedule set week_no = 8, subject = '머신러닝 및 딥러닝 이해', instructor = '이애본' where class_id = (select id from class_group where name = '7반') and date = date '2026-09-01';
update schedule set week_no = 8, subject = '머신러닝 및 딥러닝 이해', instructor = '이애본' where class_id = (select id from class_group where name = '7반') and date = date '2026-09-02';
update schedule set week_no = 8, subject = '머신러닝 및 딥러닝 이해', instructor = '이애본' where class_id = (select id from class_group where name = '7반') and date = date '2026-09-03';
update schedule set week_no = 9, subject = '생성형 AI 서비스 개발의 이해/활용 (LangChain)', instructor = '이미애' where class_id = (select id from class_group where name = '7반') and date = date '2026-09-09';
update schedule set week_no = 9, subject = '생성형 AI 서비스 개발의 이해/활용 (LangChain)', instructor = '이미애' where class_id = (select id from class_group where name = '7반') and date = date '2026-09-10';
update schedule set week_no = 9, subject = '생성형 AI 서비스 개발의 이해/활용 (LangChain)', instructor = '이미애' where class_id = (select id from class_group where name = '7반') and date = date '2026-09-11';
update schedule set week_no = 13, subject = 'AI Agent 설계 및 구축', instructor = '배기주' where class_id = (select id from class_group where name = '7반') and date = date '2026-10-06';
update schedule set week_no = 13, subject = 'AI Agent 설계 및 구축', instructor = '배기주' where class_id = (select id from class_group where name = '7반') and date = date '2026-10-07';
update schedule set week_no = 13, subject = 'Vector DB', instructor = '백정열' where class_id = (select id from class_group where name = '7반') and date = date '2026-10-08';
update schedule set week_no = 15, subject = '데이터 분석 mini-Project', instructor = '박병선' where class_id = (select id from class_group where name = '7반') and date = date '2026-10-19';
update schedule set week_no = 15, subject = '데이터 분석 mini-Project', instructor = '박병선' where class_id = (select id from class_group where name = '7반') and date = date '2026-10-20';
update schedule set week_no = 15, subject = 'AI Agent Capstone (MCP)', instructor = '허진경' where class_id = (select id from class_group where name = '7반') and date = date '2026-10-21';
update schedule set week_no = 15, subject = 'AI Agent Capstone (MCP)', instructor = '허진경' where class_id = (select id from class_group where name = '7반') and date = date '2026-10-22';
update schedule set week_no = 15, subject = 'AI Agent Capstone (MCP)', instructor = '허진경' where class_id = (select id from class_group where name = '7반') and date = date '2026-10-23';
update schedule set week_no = 16, subject = 'AI 서비스 개발 Mini-project', instructor = '허진경' where class_id = (select id from class_group where name = '7반') and date = date '2026-10-26';
update schedule set week_no = 16, subject = 'AI 서비스 개발 Mini-project', instructor = '허진경' where class_id = (select id from class_group where name = '7반') and date = date '2026-10-27';
update schedule set week_no = 16, subject = 'AI 서비스 개발 Mini-project', instructor = '허진경' where class_id = (select id from class_group where name = '7반') and date = date '2026-10-28';
update schedule set week_no = 4, subject = '데이터 분석을 위한 Python 이해', instructor = '백정열' where class_id = (select id from class_group where name = '8반') and date = date '2026-08-06';
update schedule set week_no = 4, subject = '데이터 분석을 위한 Python 이해', instructor = '백정열' where class_id = (select id from class_group where name = '8반') and date = date '2026-08-07';
update schedule set week_no = 6, subject = '컨테이너 이해 및 애플리케이션 컨테이너화', instructor = '조재형' where class_id = (select id from class_group where name = '8반') and date = date '2026-08-21';
update schedule set week_no = 7, subject = '컨테이너 이해 및 애플리케이션 컨테이너화', instructor = '조재형' where class_id = (select id from class_group where name = '8반') and date = date '2026-08-24';
update schedule set week_no = 7, subject = '특강(취업특강)', instructor = null where class_id = (select id from class_group where name = '8반') and date = date '2026-08-25';
update schedule set week_no = 8, subject = '머신러닝 및 딥러닝 이해', instructor = '장경희' where class_id = (select id from class_group where name = '8반') and date = date '2026-09-01';
update schedule set week_no = 8, subject = '머신러닝 및 딥러닝 이해', instructor = '장경희' where class_id = (select id from class_group where name = '8반') and date = date '2026-09-02';
update schedule set week_no = 8, subject = '머신러닝 및 딥러닝 이해', instructor = '장경희' where class_id = (select id from class_group where name = '8반') and date = date '2026-09-03';
update schedule set week_no = 9, subject = '쿠버네티스 이해 및 애플리케이션 배포', instructor = '정환열' where class_id = (select id from class_group where name = '8반') and date = date '2026-09-07';
update schedule set week_no = 9, subject = '쿠버네티스 이해 및 애플리케이션 배포', instructor = '정환열' where class_id = (select id from class_group where name = '8반') and date = date '2026-09-08';
update schedule set week_no = 9, subject = '생성형 AI 서비스 개발의 이해/활용 (LangChain)', instructor = '박창렴' where class_id = (select id from class_group where name = '8반') and date = date '2026-09-09';
update schedule set week_no = 9, subject = '생성형 AI 서비스 개발의 이해/활용 (LangChain)', instructor = '박창렴' where class_id = (select id from class_group where name = '8반') and date = date '2026-09-10';
update schedule set week_no = 9, subject = '생성형 AI 서비스 개발의 이해/활용 (LangChain)', instructor = '송영옥' where class_id = (select id from class_group where name = '8반') and date = date '2026-09-11';
update schedule set week_no = 10, subject = '실전 Feature Engineering', instructor = '박병선' where class_id = (select id from class_group where name = '8반') and date = date '2026-09-14';
update schedule set week_no = 10, subject = 'RAG Pipeline 설계 및 구축', instructor = '배기주' where class_id = (select id from class_group where name = '8반') and date = date '2026-09-18';
update schedule set week_no = 11, subject = 'RAG Pipeline 설계 및 구축', instructor = '배기주' where class_id = (select id from class_group where name = '8반') and date = date '2026-09-21';
update schedule set week_no = 11, subject = 'RAG Pipeline 설계 및 구축', instructor = '배기주' where class_id = (select id from class_group where name = '8반') and date = date '2026-09-22';
update schedule set week_no = 11, subject = '특강(취업특강), 2시 종료', instructor = '최헌영' where class_id = (select id from class_group where name = '8반') and date = date '2026-09-23';
update schedule set week_no = 14, subject = 'DevOps 이해 및 활용', instructor = '이용우' where class_id = (select id from class_group where name = '8반') and date = date '2026-10-12';
update schedule set week_no = 14, subject = 'DevOps 이해 및 활용', instructor = '이용우' where class_id = (select id from class_group where name = '8반') and date = date '2026-10-13';
update schedule set week_no = 15, subject = '데이터 분석 mini-Project', instructor = '윤재성' where class_id = (select id from class_group where name = '8반') and date = date '2026-10-19';
update schedule set week_no = 15, subject = '데이터 분석 mini-Project', instructor = '윤재성' where class_id = (select id from class_group where name = '8반') and date = date '2026-10-20';
update schedule set week_no = 15, subject = 'AI Agent Capstone (MCP)', instructor = '윤재성' where class_id = (select id from class_group where name = '8반') and date = date '2026-10-21';
update schedule set week_no = 15, subject = 'AI Agent Capstone (MCP)', instructor = '윤재성' where class_id = (select id from class_group where name = '8반') and date = date '2026-10-22';
update schedule set week_no = 15, subject = 'AI Agent Capstone (MCP)', instructor = '윤재성' where class_id = (select id from class_group where name = '8반') and date = date '2026-10-23';
update schedule set week_no = 16, subject = 'AI 서비스 개발 Mini-project', instructor = '박보경' where class_id = (select id from class_group where name = '8반') and date = date '2026-10-26';
update schedule set week_no = 16, subject = 'AI 서비스 개발 Mini-project', instructor = '박보경' where class_id = (select id from class_group where name = '8반') and date = date '2026-10-27';
update schedule set week_no = 16, subject = 'AI 서비스 개발 Mini-project', instructor = '박보경' where class_id = (select id from class_group where name = '8반') and date = date '2026-10-28';
update schedule set week_no = 16, subject = 'AI 프로젝트 방법론 (1시~)', instructor = '백정열' where class_id = (select id from class_group where name = '8반') and date = date '2026-10-29';
update schedule set week_no = 5, subject = 'Java, SpringBoot, Rest API 구현', instructor = '이용우' where class_id = (select id from class_group where name = '9반') and date = date '2026-08-10';
update schedule set week_no = 5, subject = 'Java, SpringBoot, Rest API 구현', instructor = '이용우' where class_id = (select id from class_group where name = '9반') and date = date '2026-08-11';
update schedule set week_no = 5, subject = 'Java, SpringBoot, Rest API 구현', instructor = '이용우' where class_id = (select id from class_group where name = '9반') and date = date '2026-08-12';
update schedule set week_no = 5, subject = 'Java, SpringBoot, Rest API 구현', instructor = '이용우' where class_id = (select id from class_group where name = '9반') and date = date '2026-08-13';
update schedule set week_no = 5, subject = 'Java, SpringBoot, Rest API 구현', instructor = '이용우' where class_id = (select id from class_group where name = '9반') and date = date '2026-08-14';
update schedule set week_no = 8, subject = '머신러닝 및 딥러닝 이해', instructor = '배기주' where class_id = (select id from class_group where name = '9반') and date = date '2026-09-01';
update schedule set week_no = 8, subject = '머신러닝 및 딥러닝 이해', instructor = '배기주' where class_id = (select id from class_group where name = '9반') and date = date '2026-09-02';
update schedule set week_no = 8, subject = '머신러닝 및 딥러닝 이해', instructor = '배기주' where class_id = (select id from class_group where name = '9반') and date = date '2026-09-03';
update schedule set week_no = 10, subject = '실전 Feature Engineering', instructor = '이상희' where class_id = (select id from class_group where name = '9반') and date = date '2026-09-14';
update schedule set week_no = 10, subject = '웹 서비스 개발 mini-Project', instructor = '김준범' where class_id = (select id from class_group where name = '9반') and date = date '2026-09-15';
update schedule set week_no = 10, subject = '웹 서비스 개발 mini-Project', instructor = '김준범' where class_id = (select id from class_group where name = '9반') and date = date '2026-09-16';
update schedule set week_no = 10, subject = '웹 서비스 개발 mini-Project', instructor = '김준범' where class_id = (select id from class_group where name = '9반') and date = date '2026-09-17';
update schedule set week_no = 10, subject = 'RAG Pipeline 설계 및 구축', instructor = '김성영' where class_id = (select id from class_group where name = '9반') and date = date '2026-09-18';
update schedule set week_no = 11, subject = 'RAG Pipeline 설계 및 구축', instructor = '김성영' where class_id = (select id from class_group where name = '9반') and date = date '2026-09-21';
update schedule set week_no = 11, subject = 'RAG Pipeline 설계 및 구축', instructor = '김성영' where class_id = (select id from class_group where name = '9반') and date = date '2026-09-22';
update schedule set week_no = 11, subject = '특강(취업특강), 2시 종료', instructor = null where class_id = (select id from class_group where name = '9반') and date = date '2026-09-23';
update schedule set week_no = 12, subject = '모델 서빙 및 AIOps 구성', instructor = '김성영' where class_id = (select id from class_group where name = '9반') and date = date '2026-09-30';
update schedule set week_no = 12, subject = '모델 서빙 및 AIOps 구성', instructor = '김성영' where class_id = (select id from class_group where name = '9반') and date = date '2026-10-01';
update schedule set week_no = 12, subject = '모델 서빙 및 AIOps 구성', instructor = '김성영' where class_id = (select id from class_group where name = '9반') and date = date '2026-10-02';
update schedule set week_no = 14, subject = 'DevOps 이해 및 활용', instructor = '윤재성' where class_id = (select id from class_group where name = '9반') and date = date '2026-10-12';
update schedule set week_no = 14, subject = 'DevOps 이해 및 활용', instructor = '윤재성' where class_id = (select id from class_group where name = '9반') and date = date '2026-10-13';
update schedule set week_no = 14, subject = '쿠버네티스 실무 심화', instructor = '이용우' where class_id = (select id from class_group where name = '9반') and date = date '2026-10-14';
update schedule set week_no = 14, subject = '쿠버네티스 실무 심화', instructor = '이용우' where class_id = (select id from class_group where name = '9반') and date = date '2026-10-15';
update schedule set week_no = 14, subject = '쿠버네티스 실무 심화', instructor = '이용우' where class_id = (select id from class_group where name = '9반') and date = date '2026-10-16';
update schedule set week_no = 15, subject = 'AI Agent Capstone (MCP)', instructor = '배기주' where class_id = (select id from class_group where name = '9반') and date = date '2026-10-21';
update schedule set week_no = 15, subject = 'AI Agent Capstone (MCP)', instructor = '배기주' where class_id = (select id from class_group where name = '9반') and date = date '2026-10-22';
update schedule set week_no = 15, subject = 'AI Agent Capstone (MCP)', instructor = '배기주' where class_id = (select id from class_group where name = '9반') and date = date '2026-10-23';
update schedule set week_no = 16, subject = 'AI 서비스 개발 Mini-project', instructor = '이애본' where class_id = (select id from class_group where name = '9반') and date = date '2026-10-26';
update schedule set week_no = 16, subject = 'AI 서비스 개발 Mini-project', instructor = '이애본' where class_id = (select id from class_group where name = '9반') and date = date '2026-10-27';
update schedule set week_no = 16, subject = 'AI 서비스 개발 Mini-project', instructor = '이애본' where class_id = (select id from class_group where name = '9반') and date = date '2026-10-28';
