import type { Schedule } from './types'

/**
 * 판교 1반 실제 강의 일정 — backend/src/main/resources/db/migration/V3__real_schedule.sql 에서 추출.
 * W01(2026-07-14) ~ W23(2026-12-18), 총 101일.
 */
export const REAL_SCHEDULES: Schedule[] = [
  { id: 1, date: '2026-07-14', weekday: '화', weekNo: 1, subject: '팀빌딩(이예슬), Git 이해/활용 (5h)', instructors: [{ name: '권기창', role: 'FULL_TIME' }], isLive: false },
  { id: 2, date: '2026-07-15', weekday: '수', weekNo: 1, subject: 'HTML, CSS, JavaScript', instructors: [{ name: '권기창', role: 'FULL_TIME' }], isLive: false },
  { id: 3, date: '2026-07-16', weekday: '목', weekNo: 1, subject: 'HTML, CSS, JavaScript', instructors: [{ name: '권기창', role: 'FULL_TIME' }], isLive: false },
  { id: 4, date: '2026-07-20', weekday: '월', weekNo: 2, subject: '데이터 분석 개요 및 기초통계', instructors: [{ name: '이은호', role: 'FULL_TIME' }], isLive: false },
  { id: 5, date: '2026-07-21', weekday: '화', weekNo: 2, subject: '데이터 분석 개요 및 기초통계', instructors: [{ name: '이은호', role: 'FULL_TIME' }], isLive: false },
  { id: 6, date: '2026-07-22', weekday: '수', weekNo: 2, subject: 'Prompt 설계와 Context', instructors: [{ name: '임성열', role: 'FULL_TIME' }], isLive: false },
  { id: 7, date: '2026-07-23', weekday: '목', weekNo: 2, subject: 'LLM과 Transformer 아키텍처', instructors: [{ name: '임성열', role: 'FULL_TIME' }], isLive: false },
  { id: 8, date: '2026-07-24', weekday: '금', weekNo: 2, subject: 'LLM과 Transformer 아키텍처', instructors: [{ name: '임성열', role: 'FULL_TIME' }], isLive: false },
  { id: 9, date: '2026-07-27', weekday: '월', weekNo: 3, subject: 'Java, SpringBoot, Rest API 구현', instructors: [{ name: '정윤석', role: 'FULL_TIME' }], isLive: false },
  { id: 10, date: '2026-07-28', weekday: '화', weekNo: 3, subject: 'Java, SpringBoot, Rest API 구현', instructors: [{ name: '정윤석', role: 'FULL_TIME' }], isLive: false },
  { id: 11, date: '2026-07-29', weekday: '수', weekNo: 3, subject: 'Java, SpringBoot, Rest API 구현', instructors: [{ name: '정윤석', role: 'FULL_TIME' }], isLive: false },
  { id: 12, date: '2026-07-30', weekday: '목', weekNo: 3, subject: 'Java, SpringBoot, Rest API 구현', instructors: [{ name: '정윤석', role: 'FULL_TIME' }], isLive: false },
  { id: 13, date: '2026-07-31', weekday: '금', weekNo: 3, subject: 'Java, SpringBoot, Rest API 구현', instructors: [{ name: '정윤석', role: 'FULL_TIME' }], isLive: false },
  { id: 14, date: '2026-08-03', weekday: '월', weekNo: 4, subject: '데이터 분석을 위한 Python 이해', instructors: [{ name: '박창렴', role: 'FULL_TIME' }], isLive: false },
  { id: 15, date: '2026-08-04', weekday: '화', weekNo: 4, subject: '데이터 분석을 위한 Python 이해', instructors: [{ name: '박창렴', role: 'FULL_TIME' }], isLive: false },
  { id: 16, date: '2026-08-05', weekday: '수', weekNo: 4, subject: '실전 Feature Engineering', instructors: [{ name: '박창렴', role: 'FULL_TIME' }], isLive: false },
  { id: 17, date: '2026-08-06', weekday: '목', weekNo: 4, subject: '머신러닝 및 딥러닝 이해', instructors: [{ name: '김일한', role: 'FULL_TIME' }], isLive: false },
  { id: 18, date: '2026-08-07', weekday: '금', weekNo: 4, subject: '머신러닝 및 딥러닝 이해', instructors: [{ name: '김일한', role: 'FULL_TIME' }], isLive: false },
  { id: 19, date: '2026-08-10', weekday: '월', weekNo: 5, subject: '머신러닝 및 딥러닝 이해', instructors: [{ name: '김일한', role: 'FULL_TIME' }], isLive: false },
  { id: 20, date: '2026-08-11', weekday: '화', weekNo: 5, subject: '스마트 데이터 이해 및 활용', instructors: [{ name: '양성호', role: 'FULL_TIME' }], isLive: false },
  { id: 21, date: '2026-08-12', weekday: '수', weekNo: 5, subject: '스마트 데이터 이해 및 활용', instructors: [{ name: '양성호', role: 'FULL_TIME' }], isLive: false },
  { id: 22, date: '2026-08-13', weekday: '목', weekNo: 5, subject: '스마트 데이터 이해 및 활용', instructors: [{ name: '양성호', role: 'FULL_TIME' }], isLive: false },
  { id: 23, date: '2026-08-14', weekday: '금', weekNo: 5, subject: '스마트 데이터 이해 및 활용', instructors: [{ name: '양성호', role: 'FULL_TIME' }], isLive: false },
  { id: 24, date: '2026-08-18', weekday: '화', weekNo: 6, subject: 'sLLM 구현 및 Fine Tunning', instructors: [{ name: '김범준', role: 'FULL_TIME' }], isLive: false },
  { id: 25, date: '2026-08-19', weekday: '수', weekNo: 6, subject: 'sLLM 구현 및 Fine Tunning', instructors: [{ name: '김범준', role: 'FULL_TIME' }], isLive: false },
  { id: 26, date: '2026-08-20', weekday: '목', weekNo: 6, subject: '컨테이너 이해 및 애플리케이션 컨테이너화', instructors: [{ name: '김범준', role: 'FULL_TIME' }], isLive: false },
  { id: 27, date: '2026-08-21', weekday: '금', weekNo: 6, subject: '컨테이너 이해 및 애플리케이션 컨테이너화', instructors: [{ name: '김범준', role: 'FULL_TIME' }], isLive: false },
  { id: 28, date: '2026-08-24', weekday: '월', weekNo: 7, subject: 'Front-framework: Vue.js', instructors: [{ name: '윤재성', role: 'FULL_TIME' }], isLive: false },
  { id: 29, date: '2026-08-25', weekday: '화', weekNo: 7, subject: 'Front-framework: Vue.js', instructors: [{ name: '윤재성', role: 'FULL_TIME' }], isLive: false },
  { id: 30, date: '2026-08-26', weekday: '수', weekNo: 7, subject: 'Front-framework: Vue.js', instructors: [{ name: '윤재성', role: 'FULL_TIME' }], isLive: false },
  { id: 31, date: '2026-08-27', weekday: '목', weekNo: 7, subject: 'Front-framework: Vue.js', instructors: [{ name: '윤재성', role: 'FULL_TIME' }], isLive: false },
  { id: 32, date: '2026-08-28', weekday: '금', weekNo: 7, subject: 'Spring AI', instructors: [{ name: '김범준', role: 'FULL_TIME' }], isLive: false },
  { id: 33, date: '2026-08-31', weekday: '월', weekNo: 8, subject: 'Spring AI', instructors: [{ name: '김범준', role: 'FULL_TIME' }], isLive: false },
  { id: 34, date: '2026-09-01', weekday: '화', weekNo: 8, subject: 'Spring AI', instructors: [{ name: '김범준', role: 'FULL_TIME' }], isLive: false },
  { id: 35, date: '2026-09-02', weekday: '수', weekNo: 8, subject: 'Agile 방법론 및 MSA 개발', instructors: [{ name: '박보경', role: 'FULL_TIME' }], isLive: false },
  { id: 36, date: '2026-09-03', weekday: '목', weekNo: 8, subject: 'Agile 방법론 및 MSA 개발', instructors: [{ name: '박보경', role: 'FULL_TIME' }], isLive: false },
  { id: 37, date: '2026-09-08', weekday: '화', weekNo: 9, subject: '웹 서비스 개발 mini-Project', instructors: [{ name: '김경난', role: 'FULL_TIME' }], isLive: false },
  { id: 38, date: '2026-09-09', weekday: '수', weekNo: 9, subject: '웹 서비스 개발 mini-Project', instructors: [{ name: '김경난', role: 'FULL_TIME' }], isLive: false },
  { id: 39, date: '2026-09-10', weekday: '목', weekNo: 9, subject: '웹 서비스 개발 mini-Project', instructors: [{ name: '김경난', role: 'FULL_TIME' }], isLive: false },
  { id: 40, date: '2026-09-11', weekday: '금', weekNo: 9, subject: '생성형 AI 서비스 개발의 이해/활용 (LangChain)', instructors: [{ name: '이애본', role: 'FULL_TIME' }], isLive: false },
  { id: 41, date: '2026-09-14', weekday: '월', weekNo: 10, subject: '생성형 AI 서비스 개발의 이해/활용 (LangChain)', instructors: [{ name: '김영희', role: 'FULL_TIME' }], isLive: false },
  { id: 42, date: '2026-09-15', weekday: '화', weekNo: 10, subject: '생성형 AI 서비스 개발의 이해/활용 (LangChain)', instructors: [{ name: '김영희', role: 'FULL_TIME' }], isLive: false },
  { id: 43, date: '2026-09-16', weekday: '수', weekNo: 10, subject: '모델 개발 및 최적화', instructors: [{ name: '김범준', role: 'FULL_TIME' }], isLive: false },
  { id: 44, date: '2026-09-17', weekday: '목', weekNo: 10, subject: '모델 개발 및 최적화', instructors: [{ name: '김범준', role: 'FULL_TIME' }], isLive: false },
  { id: 45, date: '2026-09-18', weekday: '금', weekNo: 10, subject: '쿠버네티스 이해 및 애플리케이션 배포', instructors: [{ name: '이상희', role: 'FULL_TIME' }], isLive: false },
  { id: 46, date: '2026-09-21', weekday: '월', weekNo: 11, subject: '쿠버네티스 이해 및 애플리케이션 배포', instructors: [{ name: '이상희', role: 'FULL_TIME' }], isLive: false },
  { id: 47, date: '2026-09-22', weekday: '화', weekNo: 11, subject: '모델 서빙 및 AIOps 구성', instructors: [{ name: '이상희', role: 'FULL_TIME' }], isLive: false },
  { id: 48, date: '2026-09-28', weekday: '월', weekNo: 12, subject: '모델 서빙 및 AIOps 구성', instructors: [{ name: '이상희', role: 'FULL_TIME' }], isLive: false },
  { id: 49, date: '2026-09-29', weekday: '화', weekNo: 12, subject: '모델 서빙 및 AIOps 구성', instructors: [{ name: '이상희', role: 'FULL_TIME' }], isLive: false },
  { id: 50, date: '2026-09-30', weekday: '수', weekNo: 12, subject: 'RAG Pipeline 설계 및 구축', instructors: [{ name: '하만석', role: 'FULL_TIME' }], isLive: false },
  { id: 51, date: '2026-10-01', weekday: '목', weekNo: 12, subject: 'RAG Pipeline 설계 및 구축', instructors: [{ name: '하만석', role: 'FULL_TIME' }], isLive: false },
  { id: 52, date: '2026-10-02', weekday: '금', weekNo: 12, subject: 'RAG Pipeline 설계 및 구축', instructors: [{ name: '하만석', role: 'FULL_TIME' }], isLive: false },
  { id: 53, date: '2026-10-06', weekday: '화', weekNo: 13, subject: 'Vector DB', instructors: [{ name: '하만석', role: 'FULL_TIME' }], isLive: false },
  { id: 54, date: '2026-10-07', weekday: '수', weekNo: 13, subject: '쿠버네티스 실무 심화', instructors: [{ name: '조재형', role: 'FULL_TIME' }], isLive: false },
  { id: 55, date: '2026-10-08', weekday: '목', weekNo: 13, subject: '쿠버네티스 실무 심화', instructors: [{ name: '조재형', role: 'FULL_TIME' }], isLive: false },
  { id: 56, date: '2026-10-12', weekday: '월', weekNo: 14, subject: '쿠버네티스 실무 심화', instructors: [{ name: '조재형', role: 'FULL_TIME' }], isLive: false },
  { id: 57, date: '2026-10-13', weekday: '화', weekNo: 14, subject: '데이터 분석 mini-Project', instructors: [{ name: '장경희', role: 'FULL_TIME' }], isLive: false },
  { id: 58, date: '2026-10-14', weekday: '수', weekNo: 14, subject: '데이터 분석 mini-Project', instructors: [{ name: '장경희', role: 'FULL_TIME' }], isLive: false },
  { id: 59, date: '2026-10-15', weekday: '목', weekNo: 14, subject: 'AI Agent 설계 및 구축', instructors: [{ name: '장경희', role: 'FULL_TIME' }], isLive: false },
  { id: 60, date: '2026-10-16', weekday: '금', weekNo: 14, subject: 'AI Agent 설계 및 구축', instructors: [{ name: '장경희', role: 'FULL_TIME' }], isLive: false },
  { id: 61, date: '2026-10-19', weekday: '월', weekNo: 15, subject: 'AI Agent Capstone (MCP)', instructors: [{ name: '하만석', role: 'FULL_TIME' }], isLive: false },
  { id: 62, date: '2026-10-20', weekday: '화', weekNo: 15, subject: 'AI Agent Capstone (MCP)', instructors: [{ name: '하만석', role: 'FULL_TIME' }], isLive: false },
  { id: 63, date: '2026-10-21', weekday: '수', weekNo: 15, subject: 'AI Agent Capstone (MCP)', instructors: [{ name: '하만석', role: 'FULL_TIME' }], isLive: false },
  { id: 64, date: '2026-10-22', weekday: '목', weekNo: 15, subject: 'AI 서비스 개발 Mini-project', instructors: [{ name: '하만석', role: 'FULL_TIME' }], isLive: false },
  { id: 65, date: '2026-10-23', weekday: '금', weekNo: 15, subject: 'AI 서비스 개발 Mini-project', instructors: [{ name: '하만석', role: 'FULL_TIME' }], isLive: false },
  { id: 66, date: '2026-10-26', weekday: '월', weekNo: 16, subject: 'AI 서비스 개발 Mini-project', instructors: [{ name: '하만석', role: 'FULL_TIME' }], isLive: false },
  { id: 67, date: '2026-10-27', weekday: '화', weekNo: 16, subject: 'DevOps 이해 및 활용', instructors: [{ name: '김범준', role: 'FULL_TIME' }], isLive: false },
  { id: 68, date: '2026-10-28', weekday: '수', weekNo: 16, subject: 'DevOps 이해 및 활용', instructors: [{ name: '김범준', role: 'FULL_TIME' }], isLive: false },
  { id: 69, date: '2026-11-02', weekday: '월', weekNo: 17, subject: '팀프로젝트', instructors: [{ name: '이미애', role: 'FULL_TIME' }], isLive: false },
  { id: 70, date: '2026-11-03', weekday: '화', weekNo: 17, subject: '팀프로젝트', instructors: [{ name: '이미애', role: 'FULL_TIME' }], isLive: false },
  { id: 71, date: '2026-11-04', weekday: '수', weekNo: 17, subject: '팀프로젝트', instructors: [{ name: '임성열', role: 'FULL_TIME' }], isLive: false },
  { id: 72, date: '2026-11-05', weekday: '목', weekNo: 17, subject: '팀프로젝트', instructors: [{ name: '임성열', role: 'FULL_TIME' }], isLive: false },
  { id: 73, date: '2026-11-09', weekday: '월', weekNo: 18, subject: '팀프로젝트', instructors: [{ name: '박병선', role: 'FULL_TIME' }], isLive: false },
  { id: 74, date: '2026-11-10', weekday: '화', weekNo: 18, subject: '팀프로젝트', instructors: [{ name: '백정열', role: 'FULL_TIME' }], isLive: false },
  { id: 75, date: '2026-11-11', weekday: '수', weekNo: 18, subject: '팀프로젝트', instructors: [{ name: '백정열', role: 'FULL_TIME' }], isLive: false },
  { id: 76, date: '2026-11-12', weekday: '목', weekNo: 18, subject: '팀프로젝트', instructors: [{ name: '이은호', role: 'FULL_TIME' }], isLive: false },
  { id: 77, date: '2026-11-13', weekday: '금', weekNo: 18, subject: '팀프로젝트', instructors: [{ name: '이은호', role: 'FULL_TIME' }], isLive: false },
  { id: 78, date: '2026-11-16', weekday: '월', weekNo: 19, subject: '팀프로젝트', instructors: [{ name: '박병선', role: 'FULL_TIME' }], isLive: false },
  { id: 79, date: '2026-11-17', weekday: '화', weekNo: 19, subject: '팀프로젝트', instructors: [{ name: '백정열', role: 'FULL_TIME' }], isLive: false },
  { id: 80, date: '2026-11-18', weekday: '수', weekNo: 19, subject: '팀프로젝트', instructors: [{ name: '이현민', role: 'FULL_TIME' }], isLive: false },
  { id: 81, date: '2026-11-19', weekday: '목', weekNo: 19, subject: '팀프로젝트', instructors: [{ name: '이현민', role: 'FULL_TIME' }], isLive: false },
  { id: 82, date: '2026-11-23', weekday: '월', weekNo: 20, subject: '팀프로젝트', instructors: [{ name: '이용우', role: 'FULL_TIME' }], isLive: false },
  { id: 83, date: '2026-11-24', weekday: '화', weekNo: 20, subject: '팀프로젝트', instructors: [{ name: '이용우', role: 'FULL_TIME' }], isLive: false },
  { id: 84, date: '2026-11-25', weekday: '수', weekNo: 20, subject: '팀프로젝트', instructors: [{ name: '이미애', role: 'FULL_TIME' }], isLive: false },
  { id: 85, date: '2026-11-26', weekday: '목', weekNo: 20, subject: '팀프로젝트', instructors: [{ name: '배기주', role: 'FULL_TIME' }], isLive: false },
  { id: 86, date: '2026-11-27', weekday: '금', weekNo: 20, subject: '팀프로젝트', instructors: [{ name: '이용우', role: 'FULL_TIME' }], isLive: false },
  { id: 87, date: '2026-11-30', weekday: '월', weekNo: 21, subject: '팀프로젝트', instructors: [{ name: '이은호', role: 'FULL_TIME' }], isLive: false },
  { id: 88, date: '2026-12-01', weekday: '화', weekNo: 21, subject: '팀프로젝트', instructors: [{ name: '이은호', role: 'FULL_TIME' }], isLive: false },
  { id: 89, date: '2026-12-02', weekday: '수', weekNo: 21, subject: '팀프로젝트', instructors: [{ name: '정윤석', role: 'FULL_TIME' }], isLive: false },
  { id: 90, date: '2026-12-03', weekday: '목', weekNo: 21, subject: '팀프로젝트', instructors: [{ name: '정윤석', role: 'FULL_TIME' }], isLive: false },
  { id: 91, date: '2026-12-04', weekday: '금', weekNo: 21, subject: '팀프로젝트', instructors: [{ name: '정윤석', role: 'FULL_TIME' }], isLive: false },
  { id: 92, date: '2026-12-07', weekday: '월', weekNo: 22, subject: '팀프로젝트', instructors: [{ name: '이미애', role: 'FULL_TIME' }], isLive: false },
  { id: 93, date: '2026-12-08', weekday: '화', weekNo: 22, subject: '팀프로젝트', instructors: [{ name: 'SK', role: 'FULL_TIME' }], isLive: false },
  { id: 94, date: '2026-12-09', weekday: '수', weekNo: 22, subject: '팀프로젝트', instructors: [{ name: '이미애', role: 'FULL_TIME' }], isLive: false },
  { id: 95, date: '2026-12-10', weekday: '목', weekNo: 22, subject: '팀프로젝트', instructors: [{ name: '이용우', role: 'FULL_TIME' }], isLive: false },
  { id: 96, date: '2026-12-11', weekday: '금', weekNo: 22, subject: '팀프로젝트', instructors: [{ name: '이용우', role: 'FULL_TIME' }], isLive: false },
  { id: 97, date: '2026-12-14', weekday: '월', weekNo: 23, subject: '팀프로젝트', instructors: [{ name: '최진철', role: 'FULL_TIME' }], isLive: false },
  { id: 98, date: '2026-12-15', weekday: '화', weekNo: 23, subject: '팀프로젝트', instructors: [{ name: '백정열', role: 'FULL_TIME' }], isLive: false },
  { id: 99, date: '2026-12-16', weekday: '수', weekNo: 23, subject: '팀프로젝트', instructors: [{ name: '백정열', role: 'FULL_TIME' }], isLive: false },
  { id: 100, date: '2026-12-17', weekday: '목', weekNo: 23, subject: '최종평가(예선)', instructors: [{ name: '권기창', role: 'FULL_TIME' }], isLive: false },
  { id: 101, date: '2026-12-18', weekday: '금', weekNo: 23, subject: '최종평가(본선) / 수료식 (12시 종료)', instructors: [{ name: '권기창', role: 'FULL_TIME' }], isLive: false },
]
